# Generated by Django 5.2.4 on 2025-07-05 15:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0002_dailysummary_rename_drop_location_trip_destination_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysummary',
            name='total_trips',
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='trip_count',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
