# Generated by Django 5.2.1 on 2025-07-12 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0003_remove_dailysummary_total_trips_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dailysummary',
            name='total_earnings',
        ),
        migrations.RemoveField(
            model_name='dailysummary',
            name='trip_count',
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='hours_worked',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='ola_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='ola_trips',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='rapido_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='rapido_trips',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='uber_earnings',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='dailysummary',
            name='uber_trips',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='trip',
            name='platform',
            field=models.CharField(choices=[('ola', 'Ola'), ('uber', 'Uber'), ('rapido', 'Rapido')], default='uber', max_length=10),
            preserve_default=False,
        ),
    ]
