# Generated by Django 5.2.1 on 2025-07-12 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0004_remove_dailysummary_total_earnings_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailysummary',
            name='manual_total_income',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Use this if you want to override and enter a total amount directly.', max_digits=10),
        ),
    ]
