# Generated by Django 5.2.1 on 2025-07-13 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('travel', '0005_dailysummary_manual_total_income'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyExpense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('petrol_cng_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('basic_expense', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
            ],
        ),
    ]
